version: "3.8"

services:

  postgres:
    restart: unless-stopped
    image: postgres:9.5-alpine
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - app_network

  adminer:
    restart: unless-stopped
    image: adminer
    ports:
      - 6543:8080
    networks:
      - app_network

  go_application:
    restart: unless-stopped
    build: "."
    depends_on:
      - "postgres"
    volumes:
      - "preview-images:/var/www/files-preview"
      - "model-files:/var/www/files-model"
    networks:
      - app_network

  nginx:
    restart: unless-stopped
    build: "./.nginx"
    container_name: rguide_backend
    depends_on:
      - "go_application"
    ports:
      - "80:80"
    networks:
      - app_network

volumes:
  postgres-data:
  preview-images:
  model-files:

networks:
  app_network:
    driver: bridge
  server:
    driver: bridge
