version: "3.8"

services:

  postgres:
    image: postgres:9.5-alpine
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - app_network
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 6543:8080
    networks:
      - app_network

volumes:
  postgres-data:

networks:
  app_network:
    driver: bridge
