version: "3.8"

services:

  postgres:
    image: postgres:9.5-alpine
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - app_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 6543:8080
    networks:
      - app_network

  go_application:
    build: "../"
    depends_on:
      - "postgres"
    volumes:
      - "preview-images:/var/www/preview-images"
      - "model-files:/var/www/model-files"
    networks:
      - app_network
    ports:
      - 8010:8010

volumes:
  postgres-data:
  preview-images:
  model-files:

networks:
  app_network:
    driver: bridge
